battleship: Source.o initBoard.o getGuess.o
	gcc -o battleship Source.o initBoard.o getGuess.o
Source.o: Source.c
	gcc -c Source.c
initBoard.o: initBoard.s
	gcc -c initBoard.s
getGuess.o: getGuess.s
	gcc -c getGuess.s
	

	
